spring:
  cloud:
    stream:
      binders:
        boss:
          type: rabbit
      bindings:
        event-out:
          destination: queue.order.event
        event-in-book:
          destination: queue.book.event
  rabbitmq:
    username: janwee
    password: janwee
#    addresses: 192.168.136.133:5672
    addresses: 192.168.29.130:5672